### ISSUE TITLE
'ERR_PACKAGE_PATH_NOT_EXPORTED'

### ISSUE THREAD

**Issue by jamesb93** [pngwn/sapper-mdsvex-template#14]
I have a long working project with mdsvex and sapper. After running `yarn run dev` today I get this error:

```
node:internal/process/promises:227
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './compiler.js' is not defined by "exports" in /Users/james/dev/webdev/phd-sapper/node_modules/svelte/package.json
    at new NodeError (node:internal/errors:329:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:315:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:540:3)
    at resolveExports (node:internal/modules/cjs/loader:473:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:513:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:911:27)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/james/dev/webdev/phd-sapper/node_modules/rollup-plugin-svelte/index.js:11:4) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
error Command failed with exit code 1.
```

I have tried using the `package.json` from the `npx` command here: https://github.com/pngwn/sapper-mdsvex-template
but I still get the error after trashing `node_modules` the `yarn.lock` and reinstall all the modules with `yarn`. Default projects work, but I cannot seem to figure out where my project differs.

You can view the code here:

https://github.com/jamesb93/phd-sapper

**Comment by pngwn** [comment]
This looks like a problem caused by a more recent node version. 

Could you try updating your svelte version to latest and seeing if this error persists?

**Comment by jamesb93** [comment]
I tried `yarn upgrade svelte` and `yarn upgrade svelte --latest` with no luck. I think you are right though, I did `brew update && brew upgrade` recently so thats the only moving part here.

**Comment by jamesb93** [comment]
Oh, and yes. I am using node 15.7.

**Comment by pngwn** [comment]
Could you also try updating `rollup-plugin-svelte`? That seems to be source of the error.

I know what this is, I'm just not sure where it is coming from. I'll debug a little more later with a later version of node.

**Comment by jamesb93** [comment]
Okay some progress! These warnings appear amongst some recommendations on unused CSS.
```
[rollup-plugin-svelte] Unknown "dev" option. Please use "compilerOptions" for any Svelte compiler configuration.
[rollup-plugin-svelte] Unknown "hydratable" option. Please use "compilerOptions" for any Svelte compiler configuration.
[rollup-plugin-svelte] Unknown "hydratable" option. Please use "compilerOptions" for any Svelte compiler configuration.
[rollup-plugin-svelte] Unknown "generate" option. Please use "compilerOptions" for any Svelte compiler configuration.
[rollup-plugin-svelte] Unknown "dev" option. Please use "compilerOptions" for any Svelte compiler configuration.
```

And my site now shows:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/13281862/106383573-c1b91380-63be-11eb-93e1-f3a97105ebe0.png">

**Comment by pngwn** [comment]
The plot thickens.

**Comment by jamesb93** [comment]
Indeed! Let me know what else to try and test if you have the time to spare.

**Comment by jamesb93** [comment]
Oh and some more info from the same error:

```
Error: Cannot find module '/Users/james/dev/webdev/phd-sapper/__sapper__/dev/server/server.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by jamesb93** [comment]
Would it be worth me just rolling back Node to a version you know works?

**Comment by jamesb93** [comment]
Okay I rolled back to 14.15.4 x64 builds. I then found [this issue](https://github.com/Samuel-Martineau/generator-svelte/issues/7) which details the same issue. Updating rollup-plugin-svelte to 6.1.1 fixed the problem, while updating to the latest did not.

**Comment by jamesb93** [comment]
Going to close this as it seems its about managing the Rollup/Svelte version appropriately :)
